.gitignore, Makefile, Pipfile, Pipfile.lock
I noticed after bringing the new changes from the `dev` branch that the tests were failing, presumably because an older `.so` binary was being used (the errors were pointing to object missing fields added in recent commits)
- Install nativepython in editable mode
- Remove the *.so file under typed_python during clean-up
- Ignore the .python-version file
- Ran `make clean`
- Made sure that the `*.so` files were gone
- Ran the tests with `make test` and watched them fail because of the missing `*.so` file
- Ran `make install` to re-build the package
- Ran `make test` and confirmed that all the tests passed.
=> Build process fixups

.gitignore, Makefile, object_database/algebraic_protocol.py, object_database/algebraic_protocol_test.py, object_database/database_frontend_test.py, object_database/database_test.py, object_database/frontends/database_server.py, object_database/frontends/object_database_webtest.py, object_database/frontends/service_entrypoint.py, object_database/frontends/service_manager.py, object_database/server.py, object_database/service_manager/ServiceManager_test.py, object_database/tcp_server.py, object_database/util.py, object_database/web/ActiveWebService_test.py
We want to use SSL to encrypt communications between the server and the workers (its clients). We only care about encrypting the communication, and not about making sure that the server authenticates with the clients. (This allows a man-in-the-middle attack, but we don't care about that at the moment).
the `TcpServer()` object constructor now requires an SSL context. We create such an SSL context from a self-signed SSL cert. The `connect` method didn't need to change because, for the time being, we just want encryption and not authentication, therefore the clients generate a permissive SSL context which does not authenticate the server.
All tests pass
=> Enable and mandate the use of SSL

Pipfile, Pipfile.lock
Added missing dependency `boto3`. Tests started failing because of this missing dependency after the latest updates in `dev`
=> Refreshing `Pipfile.lock`

MANIFEST.in, Pipfile, Pipfile.lock, logging.yaml, object_database/algebraic_protocol.py, object_database/database_connection.py, object_database/database_ring_invariant_test.py, object_database/database_test.py, object_database/frontends/service_entrypoint.py, object_database/frontends/service_manager.py, object_database/inmem_server.py, object_database/persistence.py, object_database/server.py, object_database/service_manager/Codebase.py, object_database/service_manager/ServiceInstance.py, object_database/service_manager/ServiceManager.py, object_database/service_manager/ServiceManager_test.py, object_database/service_manager/ServiceWorker.py, object_database/service_manager/SubprocessServiceManager.py, object_database/service_manager/aws/AwsWorkerBootService.py, object_database/tcp_server.py, object_database/util.py, object_database/view.py, object_database/web/ActiveWebService.py, object_database/web/cells.py, test.py, typed_python/Codebase.py
1. Use `self._logger = logging.getLogger(__name__)` to get a file-specific logger for finer control
2. Use `logging.config.dictConfig(...)` instead of `logging.basicConfig(...)` to configure how logging will look. This is more robust and a lot of the configuration can live in the config file (i.e., not in code), but we can still modify configs on the fly as is done in object_database.util::configureLogging
=> Tidy-up our logging

typed_python/SerializationContext.py, typed_python/types_serialization_test.py
1. Assert that we are not initializing the context with an empty name
2. Assert that the names are strings
3. Query the user-defined names before the `builtins`. This should not matter because we the builtin names start with a dot (.), but it is still preferable.
=> SerializationContext fixups

.gitignore, Makefile
Using `virtualenv` to manage virtual environment. `pipenv` operates inside the manually created virtual environment.
With this we should be able to stop using `test.py` to build the project.
=> Makefile manages local virtual environment

typed_python/Instance.hpp, typed_python/Type.cpp, typed_python/Type.hpp, typed_python/_types.cc, typed_python/class_types_test.py, typed_python/internals.py, typed_python/native_instance_wrapper.cc, typed_python/native_instance_wrapper.h
To allow us doing things like this:
```
class MyClass(Class):
x = Member(float, 3.14)
y = Message(str, "Here be dragons")
```
`HeldClass` holds an `Instance` along with each member `Type` and we unwrap `PyObject*` that comes from the python side to an `Instance` object on the C side.
- `native_instance_wrapper::tryUnwrapPyObjectToInstance` should probably be `static Instance Instance::create(PyObject* o)` , right?
- Renamed `isTypedPythonType`  to `isNativeType` to follow more closely the naming style of the rest of the code.
=> Members with default values

typed_python/SerializationBuffer.hpp
These were found while investigating failing Travis CI tests
We need to save the id in a local variable because the evaluation order
of subexpressions in C is undefined, and so with different compilers the
size() [==right hand side of the expression] was not always evaluated
before increasing the size of the vector to assign the new element.
Also we had potential INCREFs without a matching DECREF
=>  serialization bug

object_database/database_test.py
Things take longer on Travis and the `PERFORMANCE_FACTOR` had been
implemented for the tests that were failing the most, but another one
failed today, so I applied the same concept to the remaining tests in that
file, which seems to be making Travis happy
=> Use PERFORMANCE_FACTOR throughout `database_test.py` tests

nativepython/llvm_compiler.py, nativepython/native_ast_to_llvm.py, nativepython/tests/arithmetic_compilation_test.py, object_database/algebraic_protocol.py, object_database/database_connection.py, object_database/frontends/aws_config.py, object_database/frontends/service_manager.py, object_database/inmem_server.py, object_database/server.py, object_database/service_manager/Codebase.py, object_database/service_manager/ServiceManager_test.py, object_database/service_manager/ServiceWorker.py, object_database/service_manager/SubprocessServiceManager.py, object_database/service_manager/aws/AwsWorkerBootService.py, object_database/tcp_server.py, object_database/util.py, object_database/view.py, object_database/web/ActiveWebService.py, object_database/web/ActiveWebService_test.py, object_database/web/cells.py, test.py, typed_python/inspect_override.py, typed_python/python_ast.py, typed_python/types_test.py
bare `except:` statements not only catch `Exception` but also `KeyboardInterrupt` and `SystemExit` (c.f., [PEP-0348](https://www.python.org/dev/peps/pep-0348/#new-hierarchy)), which is not desirable. So, I blindly replaced `except:` with `except Exception:` everywhere.
Tests are happy, so it's probably safe to merge
=> Replace "exception:" with "exception Exception:"

setup.py
This allows `pip` (and `pipenv`) to fetch the dependencies when installing this package.
=> Declare our dependencies in setup.py

typed_python/Codebase.py, typed_python/Codebase_test.py
- `rootlevelPathFromModule` needed a fixup to work correctly when the input is a root module (such as `typed_python`)
- moving an `import` inside the function that needs it in order to avoid cyclic import problems (e.g., we could not `import typed_python.Codebase` without this change).
=> Codebase fixups

Makefile, object_database/frontends/object_database_webtest.py, object_database/object.py, object_database/test_util.py, object_database/util.py, object_database/web/ActiveWebService.py, object_database/web/ActiveWebServiceSchema.py, object_database/web/ActiveWebService_test.py, object_database/web/AuthPlugin.py, object_database/web/AuthPlugin_test.py, object_database/web/LoginPlugin.py, object_database/web/LoginPlugin_test.py, object_database/web/flask_util.py, object_database/web/templates/base.html, object_database/web/templates/error.html, typed_python/Codebase.py, typed_python/types_serialization_test.py
- Keep a record of the IP address from which the user logged in last. 
- Require re-login when the current IP does not match the login-IP.
- Refacor the login-flow of the flask-app into a `LoginPlugin`, which now becomes the consumer of the `AuthPlugins`
- The `LoginPlugin` object is responsible for registering the `login` and `logout` enpoints with the `Flask` app. It assumes that the Flask app is using the `flask-login` module to protect enpoints it needs with requiring users to be authenticated.
- When a user logs in, record their IP address in the `User` model, along with the login expiration. When checking whether a user is authenticated, compare the login IP with the current request IP.
=> Record login IP and refactor Login Plugin

.travis.yml, Pipfile, Pipfile.lock
There was a security vulnerability in the version of numpy we were using.
- `pipenv lock` to get updated dependencies
- `pipenv check` on Travis to get failed builds when new security vulnerabilities are discovered
=> ran pipenv lock to get fresh packages

setup.py
Numpy is a dependency, but the `pkg_resources` call raises if `numpy` is not already installed, creating a cyclic dependency. 
We break that dependency cycle by checking if numpy is installed.
It seems that I can once again run `pip install -r requirements.txt` with a requirements file that includes a `-e path/to/nativepython` line, without crashing.
=> Setup conditional on numpy being installed

Pipfile, Pipfile.lock, setup.py
pytz is a regular dependency, not a "dev" dependency: it is included in typed_python/SerializationContext.py which is not a test file.
- list pytz in setup.py
- move it from the "dev" to the "packages" section of the `Pipfile` dependencies
=> Pytz dependency

typed_python/PyAlternativeInstance.cpp, typed_python/PyAlternativeInstance.hpp, typed_python/PyInstance.cpp, typed_python/internals.py, typed_python/types_test.py
`Alternatives` allow us to define methods, so we should be allowed to define a `__call__` method and therefore make the alternative callable. This PR adds support for this feature
The `__call__` function is treated as a regular function, and at `tp_call` dispatch-time, we check whether the concrete alternative has a `__call__` method, and if so, we try to call it.
=> Support Callable ConcreteAlternatives

nativepython/tests/string_compilation_test.py, nativepython/type_wrappers/runtime_functions.py, nativepython/type_wrappers/string_wrapper.py, typed_python/StringType.cpp, typed_python/StringType.hpp, typed_python/_runtime.cpp, typed_python/types_test.py
* New feature: Compile str.lower() to C++ 
* Improvement: Characters that need 3 bytes to represent in UTF-8 need only 2 bytes in our String representation (rather than 4).
* Implemented C++ function on type String, defined runtime function to call from python, and when compiling, create the appropriate call in String wrapper.
* str.lower() is compiled and tested with various UTF-8 ranges
* str.lower() is tested with too many arguments, asserted to generate same TypeError as python code.
* General test strings for all string functions have been adjusted to include more UTF-8 boundary cases.
=> Compile str.lower() to C++

nativepython/tests/string_compilation_test.py, nativepython/type_wrappers/runtime_functions.py, nativepython/type_wrappers/string_wrapper.py, typed_python/StringType.cpp, typed_python/StringType.hpp, typed_python/_runtime.cpp
* New feature: compile str.find() to C++
* Implemented C++ functions of type String, one for each possible number of parameters, e.g. str.find(s, sub), str.find(s, sub, start), and str.find(s,sub, start, end)
* Defined corresponding runtime functions to call from python, and when compiling, create the appropriate call in String wrapper, according to the number of arguments provided.
* Functionality is there, but not necessarily performant, at least in the tests I've done so far.
* Tested on empty, small, and large base strings and substrings.
* Vary start and end over a wide range of values.
* Test too few and too many arguments. Raise TypeError in these cases.
- [x ] New feature (non-breaking change which adds functionality)
=> Compile str.find()

requirements.txt
bs4 is a dummy package to prevent squatting the name, but beautifulsoup4
is the official name of the package, and we were using that name in the
Pipfile, so let's be consistent and avoid the dummy dependency.
renamed bs4 -> beautifulsoup4 in `requirements.txt`
=> Use official name of beautifulsoup4

.gitignore, tox.ini
New and improved setup.py creates an `.eggs` directory. Ignore it when linting and when running `git status`
Add `.eggs` to `.gitignore` and to `tox.ini`
Manually ran the following commands with the repo checked out at this commit and checked I didn't get any lint errors and any `git status`  output:
```
make clean
make install
[check that I have a new .eggs dir]
make lint
git status
```
=> Ignore .eggs dir created by new setup when linting

typed_python/SerializationContext.hpp
This fixes a compilation error
```
In file included from typed_python/Type.hpp:16:
typed_python/SerializationContext.hpp:46:18: error: no template named 'shared_ptr' in namespace 'std'
virtual std::shared_ptr<ByteBuffer> compress(uint8_t* begin, uint8_t* end) const = 0;
~~~~~^
typed_python/SerializationContext.hpp:47:18: error: no template named 'shared_ptr' in namespace 'std'
virtual std::shared_ptr<ByteBuffer> decompress(uint8_t* begin, uint8_t* end) const = 0;
~~~~~^
```
I'm using Ubuntu 18.04.2 LTS with g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
=> fix missing <memory> import in SerializationContext

object_database/web/cells.py, object_database/web/html/html_gen.py, object_database/web/html/html_gen_tests.py, object_database/web/html_gen.py
The PR primarily deals with separating HTML string generation from any other object that spits out HTML.
In order to keep classes like Cells and friends as simple as possible, and to prevent easy errors on the part of programmers, it's a good idea to avoid writing HTML by hand.
With the classes introduced in this PR, we can now create elements in Python without having to worry about how the strings look or how to print children, etc.
The HTML generation classes and their tests can be found in `object_database/web/html`
The idea here is fairly simple: any class that subclasses `AbstractHTMLWriter` (for now this is only `HTMLElement` and `HTMLTextContent`) must implement a method called `print_on` whose first argument is some kind of stream.
In our case we are using `StringIO` to build …
=> HTML Generation

object_database/web/ActiveWebService.py, object_database/web/cells.py, object_database/web/cells_test.py
Cells is a bit of a leaky wrapper of a Cell tree. This PR formalizes a couple of things.
- Remove the `root` property of a `Cells` object and provide methods that operate on the contained `Cell` objects, such as `withRoot`, `childrenWithExceptions`, `findChildrenByTag`, and `findChildrenMatching`.
- Additionally, `withRoot` implements the common initialization pattern for a `Cells` object by setting the root, and optionally also the serialization context and the session state.
- Rename `SessionState`'s `ensure`, which is confusing, to `setdefault` which is less confusing because the semantics of that method mimic those of `setdefault` of dictionaries.
- Implement default tagging of `Modal` child cells, because the emerging testing pattern is to grab a tagged Modal, then find elements …
=> Some small improvements to `Cells`

object_database/frontends/object_database_webtest.py, object_database/frontends/service_entrypoint.py, object_database/frontends/service_manager.py, object_database/service_manager/ServiceManager.py, object_database/service_manager/ServiceManagerTestCommon.py, object_database/service_manager/SubprocessServiceManager.py, object_database/test_util.py, object_database/util.py, object_database/web/ActiveWebService.py
One might expect the default behavior would be for the `SubprocessServiceManager` to propagate its log-level, but it was defaulting to `INFO`, with the only other option being `ERROR` when a flag was set in its `__init__` method. This lead to the unexpected behavior of running tests with `--log-level=WARNING` but seeing a bunch of `INFO` logs, or more annoyingly setting `--log-level=DEBUG` and only seeing some of the debug logs because the SubprocessServiceManager was always stood up with `INFO` log-level.
This PR fixes these problem by propagating the log-level of the caller to the created processes unless a log-level is requested for those processes.
- `SubprocessServiceManager` accepts a `logLevelName` string to its `__init__` method and propagates it to its sub-processes.
- …
=> Propagate Log-Level to SubprocessServiceManager

nativepython/expression_conversion_context.py, nativepython/native_ast.py, nativepython/tests/conversion_test.py, nativepython/tests/list_of_compilation_test.py, nativepython/typed_expression.py
Without short-circuit conditional logic evaluating, the following condition will erroneously throw an `IndexError` (out of bounds) on empty lists:
```
if len(lst) > 0 and lst[0]:
<some_code>
```
We want to allow short-circuit conditional logic because otherwise the code above will need to be refactored to code with deeper nesting (as shown below), which is not desirable:
```
if len(lst) > 0:
if lst[0]:
<some_code>
```
Build nested scopes as we convert each element of a compound boolean (AND or OR) expression. That way intermediate expression evaluations are generated just when they are needed (in the appropriate nested scope), avoiding problems like the one in the example above
- Wrote a test derived from the example above
- Wrote a second test where the 2nd part of the boolean expression …
=> Implement short-circuit conditional logic

Makefile, setup.py
`make lib` was not working properly with the virtual-env flow because we were not adding the necessary `-I` flag to find the numpy libraries.
The way this was broken was that if after a `make install` we modified a `.cpp/.hpp` file and tried to run a test, `test.py` would try to run `make lib` which would fail saying it couldn't find the necessary numpy
headers:
```
typed_python/_types.cpp:2:10: fatal error: numpy/arrayobject.h: No such file or directory
```
Added `-I$(VIRTUAL_ENV)/lib/python3.6/site-packages/numpy/core/include` to `CPP_FLAGS`
Also did a refactoring of `Makefile` to break up some very long lines and to refactor common argument sequences (see `LINKER_FLAGS` and `SHAREDLIB_FLAGS`)
TravisCI is happy
=> Makefile: fix `make lib` rule 

typed_python/PyAlternativeInstance.cpp, typed_python/PyClassInstance.cpp, typed_python/PyClassInstance.hpp, typed_python/PyFunctionInstance.cpp, typed_python/PyFunctionInstance.hpp, typed_python/function_types_test.py, typed_python/types_test.py
When we define the `__call__` method of a type derived from `Class`, we want the objects of that type to be callable:
```       
class CallableClass(Class):
def __call__(self, *args, **kwargs):
return 42
obj = CallableClass()
self.assertEqual(obj(), 42)
```
Implement `tp_call_concrete` for PyClassInstance objects. Its implementation conveniently calls the helper method `callMemberFunction`
I wrote a unit-test which was failing before these changes but now is passing
=> Support callable Class objects

object_database/web/cells/cells.py, object_database/web/content/CellHandler.js, object_database/web/content/page.html
A fix for Popover rendering, which broke after changes to HTML generation.
Since the switch to `HTMLElement` based generation in the `Popover` cell, popover actions were not working inside the browser and were throwing a very cryptic jQuery-nested error.
The source of the problem had several aspects. The `updatePopovers()` function deals with re-rendering important information in any popover by way of internal function calls (ie, `title`, `content`, and `placement`). 
In the old setup, these functions looked for the inner HTML contents of nested `div`s in the popover target in order to get information about the title, content, and placement. It was the latter value -- `placement` -- that ended up being the root of the problem. Unlike the other functions in `popover` for content and title, …
=> Popover Bugfix

Makefile, object_database/VersionedObjectsOfType.hpp, setup.py, typed_python/PyClassInstance.cpp, typed_python/PyPointerToInstance.cpp, typed_python/PyTupleOrListOfInstance.cpp, typed_python/PythonSerializationContext.cpp, typed_python/Type.hpp, typed_python/_types.cpp, typed_python/util.cpp
Unused variables represent either left-over dead-code or indicate that we forgot to use an input into the code coming after the variable definition. It's a good idea to get warnings about them and address them.
Removed the `-Wno-unused-variable` compiler flag from `setup.py` and `Makefile`, recompiled the code and fixed all unused-variable warnings.
TravisCI is happy
=> Warn about unused variables and Fix those Warnings

object_database/frontends/object_database_webtest.py, object_database/service_manager/ServiceManager_test.py, object_database/web/cells/__init__.py, object_database/web/cells/cells.py, object_database/web/cells/cells_test.py, object_database/web/content/CellHandler.js, object_database/web/content/page.html
This PR implements an `AsyncDropdown` Cell, which is a `Dropdown` that can dynamically load the displayed contents when the dropdown is opened (as opposed to generating those contents ahead of time).
Not only is it useful to be able to put arbitrary elements inside of a Dropdown, but because some Cells require computation on the back end that could take a bit of time (relative to other UI components), it's helpful to load those inner Cells dynamically when the user opens the dropdown.
We introduce two new Cell types, `AsyncDropdown` and `AsyncDropdownContent`. The latter should not be used directly, but is instead created and bound to the former at instantiation.
An `AsyncDropdown` cell takes a function as it's constructor argument. We expect this function to do some kind of computation, …
=> Asynchronous Dropdown Cell

Makefile, typed_python/CompositeType.hpp, typed_python/DirectTypes.hpp, typed_python/DirectTypesTest.cpp, typed_python/DirectTypesTest.hpp, typed_python/GeneratedTypes.hpp, typed_python/_types.cpp, typed_python/all.cpp, typed_python/direct_types_test.py, typed_python/generate_types.py
Work towards c++ direct type corresponding to Alternative.
Attempt to handle self-references for Alternative types (but not other types of forward references)
For review.
Not complete.
Fixed OneOf template implementation.
Also, create rudimentary c++ test infrastructure, and tests for String, ListOf<>, TupleOf<>,  Dict<>, and OneOf<> types, correct bugs, and fill in any missing methods.
In the representation of an Alternative instance in c++, if a named tuple refers to the Alternative type, it is a forward reference that is resolved when the Type of the Alternative instance is calculated.
C++ tests have a single entry point cpp_tests().  Run these tests with "make cpptests".
If this is the correct approach, need to create tests for Alternative.
=> Working on direct c++ Alternative type; cpptests

object_database/service_manager/ServiceManager.py, object_database/service_manager/ServiceManagerTestCommon.py, object_database/service_manager/ServiceManager_test.py, object_database/test_util.py
ServiceManager's `waitRunning` and `waitStopped` methods had no tests, and `waitStopped` was not checking the right thing. This PR fixes that bug and adds a test for both these methods.
`not inst.isNotActive() != inst.isActive()`. We were using the 2nd form, but the first one is the correct for the check in `waitStopped`.  
The new unit-test, tests both `waitRunning` and `waitStopped`. It passes with the fix to `waitStopped` but it would fail before this change.
=> WaitFor Test

.gitignore, .travis.yml, MANIFEST.in, Pipfile, Pipfile.lock, README.md, object_database/service_manager/ServiceManagerTestCommon.py, setup.py, tox.ini, typed_python/PyInstance.cpp
Track how well our tests cover our code with `coverage` and the service `codecov`. This PR just sets up the integration to get the ball rolling, but it there will be several follow-ups needed:
- Our coverage for tests that uses subprocesses is unexpectedly low. This is because we have to take care to start the sub-processes in a particular way (which I'm not yet familiar with) so that they too will record coverage info and aggregate it back. We need to figure out how that is done separately.
- It will be nice to have a coverage badge on our README to show off our good coverage, when our coverage becomes better. I think that the above bullet is the first thing to figure out to increase our coverage, then we can think about increasing it by writing more tests.
- codecov has support for C++. …
=> Code Coverage with codecov

Pipfile.lock
We got a recommendation from Github to upgrade `urllib3` to >=1.24.2 because of a security vulnerability.
Upgraded using `pipenv lock --dev`
TravisCI
=> Upgrade `urllib3` due to security vulnerability
